version: '3'

services:
  app:
    container_name: djpatak-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env.production
    volumes:
      - .:/app
    depends_on:
      - redis
      - mongo
    command: npm start

  redis:
    container_name: redis-service
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  mongo:
    container_name: mongo-service
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongo-data: